### ISSUE TITLE
GridSearchCV vs DaskGridSearchCV

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-learn#17]
Thoughts on one name over the other?  I have a slight preference for GridSearchCV in order to make switching out imports easier (though I can also accomplish this with `import ... as ...`)

**Comment by mrocklin** [comment]
I would also be very happy with an alias.  I'll admit that my main motivation here is to get a speedup just by changing one character in the following line:

```python
from sklearn.model_selection import GridSearchCV
```

**Comment by jcrist** [comment]
Since the dask `*SearchCV` classes are scikit-learn classes with similar (but slightly different) arguments, I figured a different name would help improve clarity. My motivation for this was using both `sklearn.model_selection.GridSearchCV` and `dklearn.model_selection.GridSearchCV` in the same example. Since it seems to be convention in scikit-learn to import the classes instead of a namespace, I found myself doing `from dklearn import GridSearchCV as DaskGridSearchCV`, and decided just to change the name. I'm -0.5 on switching it back, I think the indication that it's a dask `*SearchCV` object is important, and having a different class name is needed so that the repr indicates this.

**Comment by mrocklin** [comment]
Thoughts on adding an alias?

**Comment by mrocklin** [comment]
I'm slightly against adding project names to classes generally, favoring namespaces instead.  For example `dd.DataFrame` conflicts with `pd.DataFrame` and `dask.distributed.Client` conflicts with `ipyparallel.Client`

**Comment by mrocklin** [comment]
(though that's a general comment, not one specifically for this issue)

**Comment by jcrist** [comment]
I feel like an alias would be confusing. Without looking, I'd assume `dklearn.model_selection.GridSearchCV` was the scikit-learn class and `dklearn.model_selection.DaskGridSearchCV` was the dask class (or at least that they were different things).

> I'm slightly against adding project names to classes generally, favoring namespaces instead.

In general I agree. However, looking at the examples in scikit-learn, it seems to be convention to do local imports, rather than importing a namespace. I assume this is because their namespaces are nested, and (most of) the sub-namespaces aren't imported immediately. E.g:

```python
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
...
```

In contrast, pandas and numpy are often imported as a shortened alias (e.g. `pd`) and all functionality is immediately accessible from the top namespace.

That said, because the scope of `dklearn` is just `*SearchCV` objects, I added them to the top namespace of `dklearn` (e.g. `dklearn.DaskGridSearchCV`.

I'm not sure what's best here. I appreciate being able to see code/a repr and know whether it's the scikit-learn class or the dask class. Scikit-learn has a built-in repr that is based on the class name, so having a different name is needed for them to repr differently

**Comment by mrocklin** [comment]
OK, that makes sense.  I'll just have to be less lazy and type more than one character :)
