### ISSUE TITLE
Dask Learn Fails for Random Forest Grid Search

### ISSUE THREAD

**Issue by pinjutien** [dask/dask-learn#28]
Hi,

I compare grid search between sklearn and dask-learn.
As per example documented in: https://github.com/pinjutien/grid-search, 

- dask-learn is invoked by: python dklearn_grid_search_script.py 
- scikit learn is invoked by: python sklearn_grid_search_script.py
 
Dask Learn fails with the following error:

Traceback (most recent call last):                                                                                                
  File "dklearn_grid_search_script.py", line 41, in <module>                                                                      
    grid_search.fit(X, y)                                                                                                         
  File "/home/pinju/.conda/envs/dask_env/lib/python3.5/site-packages/dask_learn-0+untagged.82.gb5f2bab-py3.5.egg/dklearn/model_se$
  File "/home/pinju/.conda/envs/dask_env/lib/python3.5/site-packages/dask/threaded.py", line 76, in get                           
    **kwargs)                                                                                                                     
  File "/home/pinju/.conda/envs/dask_env/lib/python3.5/site-packages/dask/async.py", line 493, in get_async                       
    raise(remote_exception(res, tb))                                                                                              
dask.async.IndexError: pop from empty list  

Thank you!
Pin-Ju

**Comment by jcrist** [comment]
The issue here is that scikit-learn's `get_params` isn't threadsafe. For more information, see https://github.com/scikit-learn/scikit-learn/issues/2755. For many estimators this is fine, as `get_params` isn't used inside the call to fit. However, it looks like classes that derive from `BaseEnsemble` (such as `RandomForestClassifier`) use `get_params` to fix the state of `random_state` in their base estimators.

Until this issue is fixed in scikit-learn, you can use one of the [other schedulers](http://dask.pydata.org/en/latest/scheduler-choice.html) instead. I recommend using the distributed scheduler over the multiprocessing one.

```python
from distributed import Client

# Local client uses processes by default, and sets the global scheduler
# which will be used by default
c = Client()

# or specify the scheduler directly in the constructor
DaskRandomizedSearchCV(..., get=c.get)

# For small problems, the synchronous scheduler may also be a good choice
DaskRandomizedSearchCV(..., get=dask.get)
```

**Comment by mrocklin** [comment]
@pinjutien does using the `dask.distributed.Client` solution as above resolve your problem short-term?

**Comment by pinjutien** [comment]
Yes, it works. Thanks!

**Comment by pinjutien** [comment]
Hi,

We have another issue of DaskGridSearchCV. The example is XGBRegressor (https://github.com/pinjutien/grid-search/tree/master/grid_search_issue2).

In this case, when DaskGridSearchCV is on, there is nothing showing up in dash-board( http://173.208.222.74:8866/status/).  Both Client or Executor have no dash-board showing up.

Thanks,
Pin-Ju

**Comment by mrocklin** [comment]
By default the bokeh dashboard is at port 8787.

If this doesn't help then what version of dask, distributed, and bokeh are
you using?

**Comment by jimmywan** [comment]
I was running into this problem and attempted to follow @jcrist 's solution above, but I'm confused as to how to make this actually work with GridSearchCV.

```
cpu_count = multiprocessing.cpu_count()
from distributed import Client
c = Client()
best_model = GridSearchCV(
        pipe,
        param_grid=param_grid,
        cv=10,
        scoring=my_scoring_method,
        n_jobs=cpu_count,
        get=c.getrange
)
```

I keep getting this error:
```
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by jcrist** [comment]
I assume you're running on windows. Since windows lacks `fork` support, you need to guard you script with:

```python
if __name__ == '__main__':
    your code here
```

as indicated in the error message you posted.

In your case this would look like:

```python
if __name__ == '__main__':
    cpu_count = multiprocessing.cpu_count()
    from distributed import Client
    c = Client()
    best_model = GridSearchCV(
            pipe,
            param_grid=param_grid,
            cv=10,
            scoring=my_scoring_method,
            n_jobs=cpu_count,
            get=c.getrange
    )
```

**Comment by jimmywan** [comment]
> I assume you're running on windows.

Running inside of a Linux VM.

**Comment by jcrist** [comment]
Hmmm, in that case can you open a new issue (this is unrelated to this closed issue) providing:

- The python/dask/distributed version that you're using
- A full script that reproduces the error
- The full traceback from that error

**Comment by jimmywan** [comment]
Didn't think it would matter since I'm in a VM, but I added the `if __name__ == '__main__':` block as suggested, and I do get a different error:
```
Traceback (most recent call last):
  File "myscript", line 422, in <module>
    get=c.get
TypeError: __init__() got an unexpected keyword argument 'get'
```

I noticed in the original suggestion you made above, you mentioned DaskRandomizedSearchCV, and not dask_searchcv.GridSearchCV. Does GridSearchCV not support this workaround?

Continuing on this issue for now since it does still seem directly related to the OP. I noticed the OP changed their code to use DaskRandomizedSearchCV, but I don't think that's equivalent to GridSearchCV.

My environment
```
$ conda list | egrep 'numpy|scipy|dask|scikit|distributed|python|tornado'
dask                      0.15.2                   py36_0
dask-searchcv             0.0.2+8.g2c2056d           <pip>
distributed               1.18.1                   py36_0
msgpack-python            0.4.8                    py36_0
numpy                     1.13.1                   py36_0
python                    3.6.1                         2
python-dateutil           2.6.1                    py36_0
scikit-learn              0.19.0              np113py36_0
scipy                     0.19.1              np113py36_0
tornado                   4.5.2                    py36_0
```

**Comment by jcrist** [comment]
> and I do get a different error:

The `get` parameter no longer exists since this issue was started, it was replaced with the `scheduler` parameter. In this case you don't need to specify the scheduler at all, it will default to your started `Client`. Please see [the docstring for `dask_searchcv.GridSearchCV`](http://dask-searchcv.readthedocs.io/en/latest/api.html#dask_searchcv.GridSearchCV)

> you mentioned DaskRandomizedSearchCV, and not dask_searchcv.GridSearchCV.

The class was renamed since this issue was created/closed, removing the `Dask` prefix.

> Continuing on this issue for now since it does still seem directly related to the OP.

These are different issues. The original issue was about `sklearn.get_params` not being threadsafe, which is not the issue you're having here.

---

Does the following work for you?:

```python
if __name__ == '__main__':
    from distributed import Client
    c = Client()
    best_model = GridSearchCV(
            your_estimator_here,
            param_grid=param_grid
    )
```

**Comment by jimmywan** [comment]
This is now working. Much appreciated and sorry for the trouble.

**Comment by jcrist** [comment]
No worries, glad you got it working.
